// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WeatherMessage.proto

// Protobuf Java Version: 3.25.1
package proto;

public final class WeatherMessage {
  private WeatherMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface WeatherStatusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.WeatherStatus)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 station_id = 1;</code>
     * @return The stationId.
     */
    long getStationId();

    /**
     * <code>int64 s_no = 2;</code>
     * @return The sNo.
     */
    long getSNo();

    /**
     * <code>string battery_status = 3;</code>
     * @return The batteryStatus.
     */
    java.lang.String getBatteryStatus();
    /**
     * <code>string battery_status = 3;</code>
     * @return The bytes for batteryStatus.
     */
    com.google.protobuf.ByteString
        getBatteryStatusBytes();

    /**
     * <code>int64 status_timestamp = 4;</code>
     * @return The statusTimestamp.
     */
    long getStatusTimestamp();

    /**
     * <code>.proto.Weather weather = 5;</code>
     * @return Whether the weather field is set.
     */
    boolean hasWeather();
    /**
     * <code>.proto.Weather weather = 5;</code>
     * @return The weather.
     */
    proto.WeatherMessage.Weather getWeather();
    /**
     * <code>.proto.Weather weather = 5;</code>
     */
    proto.WeatherMessage.WeatherOrBuilder getWeatherOrBuilder();
  }
  /**
   * Protobuf type {@code proto.WeatherStatus}
   */
  public static final class WeatherStatus extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.WeatherStatus)
      WeatherStatusOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use WeatherStatus.newBuilder() to construct.
    private WeatherStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WeatherStatus() {
      batteryStatus_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new WeatherStatus();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.WeatherMessage.internal_static_proto_WeatherStatus_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.WeatherMessage.internal_static_proto_WeatherStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.WeatherMessage.WeatherStatus.class, proto.WeatherMessage.WeatherStatus.Builder.class);
    }

    private int bitField0_;
    public static final int STATION_ID_FIELD_NUMBER = 1;
    private long stationId_ = 0L;
    /**
     * <code>int64 station_id = 1;</code>
     * @return The stationId.
     */
    @java.lang.Override
    public long getStationId() {
      return stationId_;
    }

    public static final int S_NO_FIELD_NUMBER = 2;
    private long sNo_ = 0L;
    /**
     * <code>int64 s_no = 2;</code>
     * @return The sNo.
     */
    @java.lang.Override
    public long getSNo() {
      return sNo_;
    }

    public static final int BATTERY_STATUS_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object batteryStatus_ = "";
    /**
     * <code>string battery_status = 3;</code>
     * @return The batteryStatus.
     */
    @java.lang.Override
    public java.lang.String getBatteryStatus() {
      java.lang.Object ref = batteryStatus_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        batteryStatus_ = s;
        return s;
      }
    }
    /**
     * <code>string battery_status = 3;</code>
     * @return The bytes for batteryStatus.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBatteryStatusBytes() {
      java.lang.Object ref = batteryStatus_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        batteryStatus_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_TIMESTAMP_FIELD_NUMBER = 4;
    private long statusTimestamp_ = 0L;
    /**
     * <code>int64 status_timestamp = 4;</code>
     * @return The statusTimestamp.
     */
    @java.lang.Override
    public long getStatusTimestamp() {
      return statusTimestamp_;
    }

    public static final int WEATHER_FIELD_NUMBER = 5;
    private proto.WeatherMessage.Weather weather_;
    /**
     * <code>.proto.Weather weather = 5;</code>
     * @return Whether the weather field is set.
     */
    @java.lang.Override
    public boolean hasWeather() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.proto.Weather weather = 5;</code>
     * @return The weather.
     */
    @java.lang.Override
    public proto.WeatherMessage.Weather getWeather() {
      return weather_ == null ? proto.WeatherMessage.Weather.getDefaultInstance() : weather_;
    }
    /**
     * <code>.proto.Weather weather = 5;</code>
     */
    @java.lang.Override
    public proto.WeatherMessage.WeatherOrBuilder getWeatherOrBuilder() {
      return weather_ == null ? proto.WeatherMessage.Weather.getDefaultInstance() : weather_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (stationId_ != 0L) {
        output.writeInt64(1, stationId_);
      }
      if (sNo_ != 0L) {
        output.writeInt64(2, sNo_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(batteryStatus_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, batteryStatus_);
      }
      if (statusTimestamp_ != 0L) {
        output.writeInt64(4, statusTimestamp_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(5, getWeather());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (stationId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, stationId_);
      }
      if (sNo_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, sNo_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(batteryStatus_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, batteryStatus_);
      }
      if (statusTimestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, statusTimestamp_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getWeather());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.WeatherMessage.WeatherStatus)) {
        return super.equals(obj);
      }
      proto.WeatherMessage.WeatherStatus other = (proto.WeatherMessage.WeatherStatus) obj;

      if (getStationId()
          != other.getStationId()) return false;
      if (getSNo()
          != other.getSNo()) return false;
      if (!getBatteryStatus()
          .equals(other.getBatteryStatus())) return false;
      if (getStatusTimestamp()
          != other.getStatusTimestamp()) return false;
      if (hasWeather() != other.hasWeather()) return false;
      if (hasWeather()) {
        if (!getWeather()
            .equals(other.getWeather())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATION_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getStationId());
      hash = (37 * hash) + S_NO_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSNo());
      hash = (37 * hash) + BATTERY_STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getBatteryStatus().hashCode();
      hash = (37 * hash) + STATUS_TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getStatusTimestamp());
      if (hasWeather()) {
        hash = (37 * hash) + WEATHER_FIELD_NUMBER;
        hash = (53 * hash) + getWeather().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.WeatherMessage.WeatherStatus parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.WeatherMessage.WeatherStatus parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.WeatherMessage.WeatherStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.WeatherMessage.WeatherStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.WeatherMessage.WeatherStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.WeatherMessage.WeatherStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.WeatherMessage.WeatherStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.WeatherMessage.WeatherStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static proto.WeatherMessage.WeatherStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static proto.WeatherMessage.WeatherStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.WeatherMessage.WeatherStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.WeatherMessage.WeatherStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.WeatherMessage.WeatherStatus prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.WeatherStatus}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.WeatherStatus)
        proto.WeatherMessage.WeatherStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.WeatherMessage.internal_static_proto_WeatherStatus_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.WeatherMessage.internal_static_proto_WeatherStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.WeatherMessage.WeatherStatus.class, proto.WeatherMessage.WeatherStatus.Builder.class);
      }

      // Construct using proto.WeatherMessage.WeatherStatus.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getWeatherFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        stationId_ = 0L;
        sNo_ = 0L;
        batteryStatus_ = "";
        statusTimestamp_ = 0L;
        weather_ = null;
        if (weatherBuilder_ != null) {
          weatherBuilder_.dispose();
          weatherBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.WeatherMessage.internal_static_proto_WeatherStatus_descriptor;
      }

      @java.lang.Override
      public proto.WeatherMessage.WeatherStatus getDefaultInstanceForType() {
        return proto.WeatherMessage.WeatherStatus.getDefaultInstance();
      }

      @java.lang.Override
      public proto.WeatherMessage.WeatherStatus build() {
        proto.WeatherMessage.WeatherStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.WeatherMessage.WeatherStatus buildPartial() {
        proto.WeatherMessage.WeatherStatus result = new proto.WeatherMessage.WeatherStatus(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(proto.WeatherMessage.WeatherStatus result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.stationId_ = stationId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.sNo_ = sNo_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.batteryStatus_ = batteryStatus_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.statusTimestamp_ = statusTimestamp_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.weather_ = weatherBuilder_ == null
              ? weather_
              : weatherBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.WeatherMessage.WeatherStatus) {
          return mergeFrom((proto.WeatherMessage.WeatherStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.WeatherMessage.WeatherStatus other) {
        if (other == proto.WeatherMessage.WeatherStatus.getDefaultInstance()) return this;
        if (other.getStationId() != 0L) {
          setStationId(other.getStationId());
        }
        if (other.getSNo() != 0L) {
          setSNo(other.getSNo());
        }
        if (!other.getBatteryStatus().isEmpty()) {
          batteryStatus_ = other.batteryStatus_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.getStatusTimestamp() != 0L) {
          setStatusTimestamp(other.getStatusTimestamp());
        }
        if (other.hasWeather()) {
          mergeWeather(other.getWeather());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                stationId_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                sNo_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                batteryStatus_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 32: {
                statusTimestamp_ = input.readInt64();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 42: {
                input.readMessage(
                    getWeatherFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long stationId_ ;
      /**
       * <code>int64 station_id = 1;</code>
       * @return The stationId.
       */
      @java.lang.Override
      public long getStationId() {
        return stationId_;
      }
      /**
       * <code>int64 station_id = 1;</code>
       * @param value The stationId to set.
       * @return This builder for chaining.
       */
      public Builder setStationId(long value) {

        stationId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 station_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStationId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        stationId_ = 0L;
        onChanged();
        return this;
      }

      private long sNo_ ;
      /**
       * <code>int64 s_no = 2;</code>
       * @return The sNo.
       */
      @java.lang.Override
      public long getSNo() {
        return sNo_;
      }
      /**
       * <code>int64 s_no = 2;</code>
       * @param value The sNo to set.
       * @return This builder for chaining.
       */
      public Builder setSNo(long value) {

        sNo_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int64 s_no = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSNo() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sNo_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object batteryStatus_ = "";
      /**
       * <code>string battery_status = 3;</code>
       * @return The batteryStatus.
       */
      public java.lang.String getBatteryStatus() {
        java.lang.Object ref = batteryStatus_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          batteryStatus_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string battery_status = 3;</code>
       * @return The bytes for batteryStatus.
       */
      public com.google.protobuf.ByteString
          getBatteryStatusBytes() {
        java.lang.Object ref = batteryStatus_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          batteryStatus_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string battery_status = 3;</code>
       * @param value The batteryStatus to set.
       * @return This builder for chaining.
       */
      public Builder setBatteryStatus(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        batteryStatus_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string battery_status = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearBatteryStatus() {
        batteryStatus_ = getDefaultInstance().getBatteryStatus();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string battery_status = 3;</code>
       * @param value The bytes for batteryStatus to set.
       * @return This builder for chaining.
       */
      public Builder setBatteryStatusBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        batteryStatus_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private long statusTimestamp_ ;
      /**
       * <code>int64 status_timestamp = 4;</code>
       * @return The statusTimestamp.
       */
      @java.lang.Override
      public long getStatusTimestamp() {
        return statusTimestamp_;
      }
      /**
       * <code>int64 status_timestamp = 4;</code>
       * @param value The statusTimestamp to set.
       * @return This builder for chaining.
       */
      public Builder setStatusTimestamp(long value) {

        statusTimestamp_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>int64 status_timestamp = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatusTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000008);
        statusTimestamp_ = 0L;
        onChanged();
        return this;
      }

      private proto.WeatherMessage.Weather weather_;
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.WeatherMessage.Weather, proto.WeatherMessage.Weather.Builder, proto.WeatherMessage.WeatherOrBuilder> weatherBuilder_;
      /**
       * <code>.proto.Weather weather = 5;</code>
       * @return Whether the weather field is set.
       */
      public boolean hasWeather() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>.proto.Weather weather = 5;</code>
       * @return The weather.
       */
      public proto.WeatherMessage.Weather getWeather() {
        if (weatherBuilder_ == null) {
          return weather_ == null ? proto.WeatherMessage.Weather.getDefaultInstance() : weather_;
        } else {
          return weatherBuilder_.getMessage();
        }
      }
      /**
       * <code>.proto.Weather weather = 5;</code>
       */
      public Builder setWeather(proto.WeatherMessage.Weather value) {
        if (weatherBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          weather_ = value;
        } else {
          weatherBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>.proto.Weather weather = 5;</code>
       */
      public Builder setWeather(
          proto.WeatherMessage.Weather.Builder builderForValue) {
        if (weatherBuilder_ == null) {
          weather_ = builderForValue.build();
        } else {
          weatherBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>.proto.Weather weather = 5;</code>
       */
      public Builder mergeWeather(proto.WeatherMessage.Weather value) {
        if (weatherBuilder_ == null) {
          if (((bitField0_ & 0x00000010) != 0) &&
            weather_ != null &&
            weather_ != proto.WeatherMessage.Weather.getDefaultInstance()) {
            getWeatherBuilder().mergeFrom(value);
          } else {
            weather_ = value;
          }
        } else {
          weatherBuilder_.mergeFrom(value);
        }
        if (weather_ != null) {
          bitField0_ |= 0x00000010;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.proto.Weather weather = 5;</code>
       */
      public Builder clearWeather() {
        bitField0_ = (bitField0_ & ~0x00000010);
        weather_ = null;
        if (weatherBuilder_ != null) {
          weatherBuilder_.dispose();
          weatherBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.proto.Weather weather = 5;</code>
       */
      public proto.WeatherMessage.Weather.Builder getWeatherBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getWeatherFieldBuilder().getBuilder();
      }
      /**
       * <code>.proto.Weather weather = 5;</code>
       */
      public proto.WeatherMessage.WeatherOrBuilder getWeatherOrBuilder() {
        if (weatherBuilder_ != null) {
          return weatherBuilder_.getMessageOrBuilder();
        } else {
          return weather_ == null ?
              proto.WeatherMessage.Weather.getDefaultInstance() : weather_;
        }
      }
      /**
       * <code>.proto.Weather weather = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.WeatherMessage.Weather, proto.WeatherMessage.Weather.Builder, proto.WeatherMessage.WeatherOrBuilder> 
          getWeatherFieldBuilder() {
        if (weatherBuilder_ == null) {
          weatherBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              proto.WeatherMessage.Weather, proto.WeatherMessage.Weather.Builder, proto.WeatherMessage.WeatherOrBuilder>(
                  getWeather(),
                  getParentForChildren(),
                  isClean());
          weather_ = null;
        }
        return weatherBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.WeatherStatus)
    }

    // @@protoc_insertion_point(class_scope:proto.WeatherStatus)
    private static final proto.WeatherMessage.WeatherStatus DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.WeatherMessage.WeatherStatus();
    }

    public static proto.WeatherMessage.WeatherStatus getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<WeatherStatus>
        PARSER = new com.google.protobuf.AbstractParser<WeatherStatus>() {
      @java.lang.Override
      public WeatherStatus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<WeatherStatus> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<WeatherStatus> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.WeatherMessage.WeatherStatus getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface WeatherOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.Weather)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>float humidity = 1;</code>
     * @return The humidity.
     */
    float getHumidity();

    /**
     * <code>float temperature = 2;</code>
     * @return The temperature.
     */
    float getTemperature();

    /**
     * <code>float wind_speed = 3;</code>
     * @return The windSpeed.
     */
    float getWindSpeed();
  }
  /**
   * Protobuf type {@code proto.Weather}
   */
  public static final class Weather extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.Weather)
      WeatherOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Weather.newBuilder() to construct.
    private Weather(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Weather() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Weather();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.WeatherMessage.internal_static_proto_Weather_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.WeatherMessage.internal_static_proto_Weather_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.WeatherMessage.Weather.class, proto.WeatherMessage.Weather.Builder.class);
    }

    public static final int HUMIDITY_FIELD_NUMBER = 1;
    private float humidity_ = 0F;
    /**
     * <code>float humidity = 1;</code>
     * @return The humidity.
     */
    @java.lang.Override
    public float getHumidity() {
      return humidity_;
    }

    public static final int TEMPERATURE_FIELD_NUMBER = 2;
    private float temperature_ = 0F;
    /**
     * <code>float temperature = 2;</code>
     * @return The temperature.
     */
    @java.lang.Override
    public float getTemperature() {
      return temperature_;
    }

    public static final int WIND_SPEED_FIELD_NUMBER = 3;
    private float windSpeed_ = 0F;
    /**
     * <code>float wind_speed = 3;</code>
     * @return The windSpeed.
     */
    @java.lang.Override
    public float getWindSpeed() {
      return windSpeed_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (java.lang.Float.floatToRawIntBits(humidity_) != 0) {
        output.writeFloat(1, humidity_);
      }
      if (java.lang.Float.floatToRawIntBits(temperature_) != 0) {
        output.writeFloat(2, temperature_);
      }
      if (java.lang.Float.floatToRawIntBits(windSpeed_) != 0) {
        output.writeFloat(3, windSpeed_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (java.lang.Float.floatToRawIntBits(humidity_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, humidity_);
      }
      if (java.lang.Float.floatToRawIntBits(temperature_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, temperature_);
      }
      if (java.lang.Float.floatToRawIntBits(windSpeed_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, windSpeed_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.WeatherMessage.Weather)) {
        return super.equals(obj);
      }
      proto.WeatherMessage.Weather other = (proto.WeatherMessage.Weather) obj;

      if (java.lang.Float.floatToIntBits(getHumidity())
          != java.lang.Float.floatToIntBits(
              other.getHumidity())) return false;
      if (java.lang.Float.floatToIntBits(getTemperature())
          != java.lang.Float.floatToIntBits(
              other.getTemperature())) return false;
      if (java.lang.Float.floatToIntBits(getWindSpeed())
          != java.lang.Float.floatToIntBits(
              other.getWindSpeed())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + HUMIDITY_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getHumidity());
      hash = (37 * hash) + TEMPERATURE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getTemperature());
      hash = (37 * hash) + WIND_SPEED_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getWindSpeed());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.WeatherMessage.Weather parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.WeatherMessage.Weather parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.WeatherMessage.Weather parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.WeatherMessage.Weather parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.WeatherMessage.Weather parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.WeatherMessage.Weather parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.WeatherMessage.Weather parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.WeatherMessage.Weather parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static proto.WeatherMessage.Weather parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static proto.WeatherMessage.Weather parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.WeatherMessage.Weather parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.WeatherMessage.Weather parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.WeatherMessage.Weather prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.Weather}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.Weather)
        proto.WeatherMessage.WeatherOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.WeatherMessage.internal_static_proto_Weather_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.WeatherMessage.internal_static_proto_Weather_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.WeatherMessage.Weather.class, proto.WeatherMessage.Weather.Builder.class);
      }

      // Construct using proto.WeatherMessage.Weather.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        humidity_ = 0F;
        temperature_ = 0F;
        windSpeed_ = 0F;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.WeatherMessage.internal_static_proto_Weather_descriptor;
      }

      @java.lang.Override
      public proto.WeatherMessage.Weather getDefaultInstanceForType() {
        return proto.WeatherMessage.Weather.getDefaultInstance();
      }

      @java.lang.Override
      public proto.WeatherMessage.Weather build() {
        proto.WeatherMessage.Weather result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.WeatherMessage.Weather buildPartial() {
        proto.WeatherMessage.Weather result = new proto.WeatherMessage.Weather(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(proto.WeatherMessage.Weather result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.humidity_ = humidity_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.temperature_ = temperature_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.windSpeed_ = windSpeed_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.WeatherMessage.Weather) {
          return mergeFrom((proto.WeatherMessage.Weather)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.WeatherMessage.Weather other) {
        if (other == proto.WeatherMessage.Weather.getDefaultInstance()) return this;
        if (other.getHumidity() != 0F) {
          setHumidity(other.getHumidity());
        }
        if (other.getTemperature() != 0F) {
          setTemperature(other.getTemperature());
        }
        if (other.getWindSpeed() != 0F) {
          setWindSpeed(other.getWindSpeed());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 13: {
                humidity_ = input.readFloat();
                bitField0_ |= 0x00000001;
                break;
              } // case 13
              case 21: {
                temperature_ = input.readFloat();
                bitField0_ |= 0x00000002;
                break;
              } // case 21
              case 29: {
                windSpeed_ = input.readFloat();
                bitField0_ |= 0x00000004;
                break;
              } // case 29
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private float humidity_ ;
      /**
       * <code>float humidity = 1;</code>
       * @return The humidity.
       */
      @java.lang.Override
      public float getHumidity() {
        return humidity_;
      }
      /**
       * <code>float humidity = 1;</code>
       * @param value The humidity to set.
       * @return This builder for chaining.
       */
      public Builder setHumidity(float value) {

        humidity_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>float humidity = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearHumidity() {
        bitField0_ = (bitField0_ & ~0x00000001);
        humidity_ = 0F;
        onChanged();
        return this;
      }

      private float temperature_ ;
      /**
       * <code>float temperature = 2;</code>
       * @return The temperature.
       */
      @java.lang.Override
      public float getTemperature() {
        return temperature_;
      }
      /**
       * <code>float temperature = 2;</code>
       * @param value The temperature to set.
       * @return This builder for chaining.
       */
      public Builder setTemperature(float value) {

        temperature_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>float temperature = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTemperature() {
        bitField0_ = (bitField0_ & ~0x00000002);
        temperature_ = 0F;
        onChanged();
        return this;
      }

      private float windSpeed_ ;
      /**
       * <code>float wind_speed = 3;</code>
       * @return The windSpeed.
       */
      @java.lang.Override
      public float getWindSpeed() {
        return windSpeed_;
      }
      /**
       * <code>float wind_speed = 3;</code>
       * @param value The windSpeed to set.
       * @return This builder for chaining.
       */
      public Builder setWindSpeed(float value) {

        windSpeed_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>float wind_speed = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearWindSpeed() {
        bitField0_ = (bitField0_ & ~0x00000004);
        windSpeed_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.Weather)
    }

    // @@protoc_insertion_point(class_scope:proto.Weather)
    private static final proto.WeatherMessage.Weather DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.WeatherMessage.Weather();
    }

    public static proto.WeatherMessage.Weather getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Weather>
        PARSER = new com.google.protobuf.AbstractParser<Weather>() {
      @java.lang.Override
      public Weather parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Weather> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Weather> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.WeatherMessage.Weather getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_WeatherStatus_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_WeatherStatus_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Weather_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Weather_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024WeatherMessage.proto\022\005proto\"\204\001\n\rWeathe" +
      "rStatus\022\022\n\nstation_id\030\001 \001(\003\022\014\n\004s_no\030\002 \001(" +
      "\003\022\026\n\016battery_status\030\003 \001(\t\022\030\n\020status_time" +
      "stamp\030\004 \001(\003\022\037\n\007weather\030\005 \001(\0132\016.proto.Wea" +
      "ther\"D\n\007Weather\022\020\n\010humidity\030\001 \001(\002\022\023\n\013tem" +
      "perature\030\002 \001(\002\022\022\n\nwind_speed\030\003 \001(\002b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_proto_WeatherStatus_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_WeatherStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_WeatherStatus_descriptor,
        new java.lang.String[] { "StationId", "SNo", "BatteryStatus", "StatusTimestamp", "Weather", });
    internal_static_proto_Weather_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_Weather_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Weather_descriptor,
        new java.lang.String[] { "Humidity", "Temperature", "WindSpeed", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
