apiVersion: v1
kind: PersistentVolume
metadata:
  name: archive-persistent-volume
spec:
  storageClassName: manual
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/mai/mnt/data"
