apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-station-deployment
  labels:
    component: station

spec:
  replicas: 1
  selector:
    matchLabels:
      component: station
  template:
    metadata:
      labels:
        component: station
    spec:
      containers:
        - name: weather-station-container
          image: weather-station-image:latest
          imagePullPolicy: Never
          env:
            - name: stationType
              value: "Mock"
            - name: stationNumber
              value: "1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-meteo-weather-station-deployment
  labels:
    component: om-station

spec:
  replicas: 1
  selector:
    matchLabels:
      component: meteo-station
  template:
    metadata:
      labels:
        component: meteo-station
    spec:
      containers:
        - name: meteo-weather-station-container
          image: weather-station-image:latest
          imagePullPolicy: Never
          env:
            - name: stationType
              value: "Meteo"
            - name: stationNumber
              value: "2"
            - name: latitude
              value: "31.78"
            - name: longitude
              value: "21.256"
